-keep class com.example.biologytester.model.** { *; }
-keepclassmembers class com.example.biologytester.model.** { *; }
-keep class retrofit2.** { *; }
-keep class com.google.gson.** { *; }
-keep class com.example.biologytester.ota.GithubRelease { *; }
-keep class com.example.biologytester.ota.GithubAsset { *; }
